# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fc395bb4a690c75d71e2699a64f848bf1293bc23857974ca67f0352b700a02a96b771f7bb33bb2588e2650294b541c0f00884b1bcabb091e93c03d38469d249

test:
  secret_key_base: 2f233d52c7ddd6d64074bc21434f3400e2598327e52032f2a3329836eeda8e742b56ced365d735149f06cbe796aefab8796480c01ac1f7f62032a44c4136b14d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
